using DrawingApp.DM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.Google;
using System.Data;
using System.Text.Json;

namespace DrawingApp.Providers
{
    /**
     * DrawingProvider Service
     * -----------------------
     * This service handles the communication with AI models (Gemini or GPT).
     * It transforms user prompts into structured JSON data for canvas rendering.
     */
    public class DrawingProvider
    {
        private readonly HttpClient _httpClient;
        private readonly Kernel _kernel;
        private readonly string _apiKey;
        private readonly string _apiUrl;
        private readonly string _connectionString;

        public DrawingProvider(HttpClient httpClient, IConfiguration configuration, Kernel kernel)
        {
            _httpClient = httpClient;
            _kernel = kernel ?? throw new ArgumentNullException(nameof(kernel));

            // Getting settings from appsettings.json
            // Make sure to update these keys in your JSON file
            _apiKey = configuration["AiSettings:ApiKey"] ?? "";
            _apiUrl = configuration["AiSettings:ApiUrl"] ?? "";
            _connectionString = configuration.GetConnectionString("DefaultConnection")
                               ?? throw new InvalidOperationException("Connection string not found.");
        }

        /**
         * Sends a natural language prompt to the AI and returns a JSON string 
         * containing shape definitions (type, color, etc.).
         * * @param prompt - The user's drawing request (e.g., "draw a red circle").
         * @returns A sanitized JSON string for the frontend.
         */
        public async Task<string> GenerateAiDrawingAsync(string userPrompt,string currentShapesJson)
        {
            try
            {

                var settings = new GeminiPromptExecutionSettings
                {
                    ResponseMimeType = "application/json",
                    ResponseSchema = typeof(DrawingResponse), // הכרחי ל-Gemini 2.5
                    Temperature = 0.1f
                };

                const string systemInstruction = @"
        You are an expert AI Drawing Assistant. 
        Your goal is to generate NEW geometric shapes based on a user's request while considering the CURRENT state of the canvas.

        STRICT RULES:
        1. Context Awareness: Analyze the 'Current Canvas State' provided. 
        2. No Overlap: Place new shapes in empty areas of the 800x600 canvas. Do not draw over existing shapes unless explicitly asked.
        3. Output Format: Return ONLY a valid JSON object. No prose, no markdown blocks.
        4. Schema:
        {
            ""shapes"": [
                {
                    ""type"": ""rect"" | ""circle"" | ""line"",
                    ""x"": number,
                    ""y"": number,
                    ""color"": string,
                    ""radius"": number (for circles),
                    ""width"": number (for rects),
                    ""height"": number (for rects),
                    ""toX"": number (for lines),
                    ""toY"": number (for lines)
                }
            ]
        }";

                var prompt = $"""
        SYSTEM INSTRUCTIONS: {systemInstruction}
        
        CURRENT CANVAS STATE (JSON): 
        {currentShapesJson}

        USER REQUEST: 
        {userPrompt}
        
        Generate only the NEW shapes to be added:
        """;

                var result = await _kernel.InvokePromptAsync(prompt, new KernelArguments(settings));
                return result.ToString();
            }
            catch (Exception ex)
            {
                // Logs the exception to the Visual Studio Output window
                Console.WriteLine($"[Critical DrawingProvider Error] {ex.Message}");

                // Fallback shape to prevent frontend crash on white canvas
                return "{\"Commands\": [{\"type\": \"rect\", \"x\": 50, \"y\": 50, \"width\": 100, \"height\": 100, \"color\": \"red\"}]}";
            }
        }

        public async Task<int> SaveDrawingToDb(string drawingDataJson)
        {
            using (var connection = new SqlConnection(_connectionString))
            {
                using (var command = new SqlCommand("sp_SaveDrawing", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    command.Parameters.AddWithValue("UserId", 1);// Replace with actual user ID from authentication context
                    //  2024-04-17_15-30-00
                    string autoGeneratedName = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
                    command.Parameters.AddWithValue("Name", autoGeneratedName);
                    command.Parameters.AddWithValue("@CommandsJson", drawingDataJson);

                    await connection.OpenAsync();

                    var result = await command.ExecuteScalarAsync();

                    return Convert.ToInt32(result);
                }
            }
        }

        public async Task<List<Drawing>> GetFullUserDrawings()
        {
            var drawings = new List<Drawing>();

            using var connection = new SqlConnection(_connectionString);
            using var command = new SqlCommand("sp_GetUserDrawings", connection);
            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@UserId", 1);// Replace with actual user ID from authentication context

            await connection.OpenAsync();
            using var reader = await command.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                drawings.Add(new Drawing
                {
                    Id = (int)reader["Id"],
                    Name = reader["Name"].ToString(),
                    CommandsJson = reader["CommandsJson"].ToString()
                });
            }
            return drawings;
        }
    }
}